#! /bin/bash

usage () {
      echo "$0: a small wrapper to generate a rpm."
      echo "Usage: $0 -d"
}

if [ "$1" != "-d" ]; then
   usage
   exit 1
fi

set -e
buildroot=$(dirname $(readlink -f "$0"))
mkdir -p ${buildroot}/{RPMS,BUILD,BUILDROOT}
rpmbuild --verbose \
    --define "_topdir ${buildroot}" \
    --define "_rpmdir ${buildroot}/RPMS" \
    -bb "${buildroot}/SPECS/yum.spec"
